version: '2'

services:
  aws-scheduled:
    image: camptocamp/aws-scheduled-maintenance:1.0
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION_NAME: ${AWS_REGION_NAME}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: monitoring=true
      io.aws_scheduled: true
  jobber:
    image: blacklabelops/jobber:docker
    environment:
      JOB_COMMAND1: 'docker start $$(docker ps -a -f label=io.aws_scheduled=true --format="{{.ID}}")'
      JOB_NAME1: aws-scheduled
      JOB_TIME1: ${JOB_SCHEDULED}
    labels:
      io.upkick.warn_only: false
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
